### ISSUE TITLE
Bad state: Stream has already been listened  in UploadedFile

### ISSUE THREAD

**Issue by insinfo** [dart-backend/angel#157]
```console
[FINE] esic: 204 OPTIONS /esicbackend/api/v1/manifestacoes-ouvidoria/responder/solicitacao (0 ms)
[INFO] esic: [Server] Called handleRawRequest
[INFO] esic: ManifestacaoOuvidoriaController@responder Bad state: Stream has already been listened to. #0      _StreamController._subscribe (dart:async/stream_controller.dart:686:7)
#1      _ControllerStream._createSubscription (dart:async/stream_controller.dart:836:19)
#2      _StreamImpl.listen (dart:async/stream_impl.dart:471:9)
#3      _MimeMultipart.listen (package:mime/src/bound_multipart_stream.dart:52:15)
#4      HttpMultipartFormData.listen (package:belatuk_http_server/src/http_multipart_form_data.dart:134:20)
#5      CastStream.listen (dart:_internal/async_cast.dart:17:17)
#6      _StreamIterator._initializeOrDone (dart:async/stream_impl.dart:999:33)
#7      _StreamIterator.moveNext (dart:async/stream_impl.dart:975:12)
#8      ManifestacaoOuvidoriaController.responderManifestacao (package:esic_backend/src/modules/manifestacao_ouvidoria/controllers/manifestacao_ouvidoria_controller.dart)
<asynchronous suspension>
#9      Angel.getHandlerResult.<anonymous closure> (package:angel3_framework/src/core/server.dart:271:27)
<asynchronous suspension>
#10     Angel.executeHandler.<anonymous closure> (package:angel3_framework/src/core/server.dart:289:53)
<asynchronous suspension>
#11     Driver.runPipeline (package:angel3_framework/src/core/driver.dart:393:22)
<asynchronous suspension>
#12     Driver.handleRawRequest.<anonymous closure>.<anonymous closure>.handle.<anonymous closure> (package:angel3_framework/src/core/driver.dart:159:21)
<asynchronous suspension>
#13     HotReloader.handleRequest (package:angel3_hot/angel3_hot.dart:119:14)
<asynchronous suspension>

[FINE] esic: 400 POST /esicbackend/api/v1/manifestacoes-ouvidoria/responder/solicitacao (14 ms)
```

```dart
import 'dart:typed_data';

import 'package:angel3_framework/angel3_framework.dart';
import 'package:esic_backend/esic_backend.dart';
import 'package:esic_backend/src/shared/services/envia_email_service.dart';
import 'package:esic_core/esic_core.dart';
import 'package:belatuk_http_server/src/http_multipart_form_data.dart';

class ManifestacaoOuvidoriaController {

 static Future<dynamic> responderManifestacao(
      RequestContext req, ResponseContext res) async {
    try {
      await req.parseBody();

      final token = req.container!.make<AuthTokenJubarte>();

      final map = await req.getDataFieldFromFormData();
      final manifestacao = ManifestacaoOuvidoria.fromMap(map);

      final usuarioRepository = req.container!.make<UsuarioRepository>();
      final usuario = await usuarioRepository.getByCpf(token.cpfPessoa);

      //mescla as referencias de arquivos ao model solicitacao
      if (req.uploadedFiles != null) {
        for (UploadedFile file in req.uploadedFiles!) {
          for (final anexo in manifestacao.anexos) {
            if (file.filename == anexo.nome) {
              final HttpMultipartFormData formData = file.formData;
              final Stream<List<int>> streamListInt =
                  formData.cast<List<int>>();
              
              final BytesBuilder bytesBuilder = BytesBuilder();

              await for (final data in streamListInt) {
                bytesBuilder.add(data);
              }

              anexo.bytes = bytesBuilder.takeBytes();

              anexo.idUsuarioInclusao = usuario.id;
              anexo.cpfUsuarioInclusao = usuario.cpfUsuario;
              anexo.nomeUsuarioInclusao = usuario.nome;
            }
          }
        }
      }

      manifestacao.idUsuarioResposta = usuario.id;
      manifestacao.cpfUsuarioResposta = usuario.cpfUsuario;
      manifestacao.nomeUsuarioResposta = usuario.nome;

      manifestacao.dataResposta = DateTime.now();
      manifestacao.idSecretariaResposta = usuario.idSecretaria;
      manifestacao.situacao = ManifestacaoStatus.respondido;

      final solicitanteRepository =
          req.container!.make<SolicitanteRepository>();

      final manifestacaoRepository =
          req.container!.make<ManifestacaoOuvidoriaRepository>();

      await manifestacaoRepository.responder(manifestacao);

      final solicitante =
          await solicitanteRepository.getById(manifestacao.idSolicitante);

      final appConfig = req.container!.make<AppConfig>();
      //envia email de aviso de reposta ao solicitante
      final emailService = EnviaEmailService();
      emailService.assunto =
          'Prefeitura de Rio das Ostras - Sua manifestação foi respondida';
      emailService.html = """Prezado(a) ${solicitante.nome},<br> <br>
Sua solicita&ccedil;&atilde;o <b>${manifestacao.protocoloFormatado}</b> foi respondida
 <br>Para mais informa&ccedil;&otilde;es acesse o sistema ${appConfig.nomeSistema} - Rio das Ostras.<br><br>
Mensagem Autom&aacute;tica do Sistema ${appConfig.nomeSistema} - Rio das Ostras
        """;
      emailService.paraEmail = solicitante.email;
      await emailService.envia();

      return res.responseJson(StatusMessage.seccessMap);
    } catch (e, s) {
      print('ManifestacaoOuvidoriaController@responder $e $s');
      return res.responseError(StatusMessage.ERROR_WHEN_UPDATE_DATA,
          exception: e, stackTrace: s);
    }
  }
}

Future configureServer(Angel app) async {
  
  final options = CorsOptions(allowedHeaders: ["*"], exposedHeaders: ["*"]);
  app.fallback(cors(options));

  await dependencyInjection(app);

  //file system config
  final fs = const LocalFileSystem();
  //routes config
  await app.configure(configureRoutes(fs));
}

AngelConfigurer configureRoutes(file.FileSystem fileSystem) {
  return (Angel app) async {
    app.get('/', (req, res) => res.write('esic_backend'));
    app.get(
        '/confirmacao', (req, res) => SolicitanteController.confirmaCadastro);
    app.group(AppConfig.inst().basePath, (router) async {
        
      await manifestacaoOuvidoriaPublicRoutes(router);
    
    });

    app.chain([AuthMiddleware().handleRequest]).group(AppConfig.inst().basePath,
        (router) async {
   
      await manifestacaoOuvidoriaPrivatesRoutes(router);
    
    });

    if (!app.environment.isProduction) {
      var vDir = static_file_server.VirtualDirectory(
        app,
        fileSystem,
        source: fileSystem.directory('web'),
      );
      app.fallback(vDir.handleRequest);
    }

    app.fallback((req, res) {
      res.headers['Content-Type'] = 'application/json;charset=utf-8';
      res.statusCode = 404;
      return res.write(jsonEncode({
        'message': 'Rota não existe',
        'exception': 'Rota não existe',
        'stackTrace': ''
      }));
    });

    var oldErrorHandler = app.errorHandler;
    app.errorHandler = (e, req, res) async {
      if (req.accepts('text/html', strict: true)) {
        if (e.statusCode == 404 && req.accepts('text/html', strict: true)) {
          await res
              .render('error', {'message': 'Arquivo não existe ${req.uri}.'});
        } else {
          await res.render('error', {'message': e.message});
        }
      } else {
        return await oldErrorHandler(e, req, res);
      }
    };
  };
}

Future<dynamic> manifestacaoOuvidoriaPrivatesRoutes(Router app) async {
  // lista tipos de manifestação de ouvidoria
  app.get('/tipo-manifestacoes-ouvidoria',
      (req, res) => TipoManifestacaoOuvidoriaController.getAll);

  // lista todas as manifestações
  app.get('/manifestacoes-ouvidoria',
      (req, res) => ManifestacaoOuvidoriaController.getAll);
  // lista todas as manifestações do solicitante logado
  app.get('/manifestacoes-ouvidoria/usuario/logado',
      (req, res) => ManifestacaoOuvidoriaController.getAllBySolicitante);
  // obtem uma unica manifestação por id de manifestação
  app.get('/manifestacoes-ouvidoria/:id',
      (req, res) => ManifestacaoOuvidoriaController.getById);
  // obtem uma unica manifestação por id de manifestação e garantindo que so traz se for do solicitante logado
  app.get(
      '/manifestacoes-ouvidoria/usuario/:id',
      (req, res) =>
          ManifestacaoOuvidoriaController.getByIdManifestacaoAndSolicitante);

  // cadastra uma manifestação
  app.post('/manifestacoes-ouvidoria',
      (req, res) => ManifestacaoOuvidoriaController.insert);
      
  // prorroga uma manifestação
  app.post('/manifestacoes-ouvidoria/prorrogar/solicitacao',
      (req, res) => ManifestacaoOuvidoriaController.prorrogar);
  // responde uma manifestação
  app.post('/manifestacoes-ouvidoria/responder/solicitacao',
      (req, res) => ManifestacaoOuvidoriaController.responderManifestacao);
  // muda o status de uma manifestação para recebido
  app.post('/manifestacoes-ouvidoria/receber/solicitacao',
      (req, res) => ManifestacaoOuvidoriaController.receber);
}

Future<dynamic> manifestacaoOuvidoriaPublicRoutes(Router app) async {}
```

**Comment by insinfo** [comment]
sorry, I found out the problem was my implementation failure
